version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    volumes: 
      - ./config:/etc/prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"